import Foundation
import UniformTypeIdentifiers

/// Handles CSV and JSON export/import for dive log data
struct ExportService {

    // MARK: - CSV Export

    static func generateCSV(from dives: [Dive]) -> String {
        var csv = "Date,Location,Dive Site,Max Depth (ft),Bottom Time (min),Water Temp (°F),Visibility (ft),Buddy,Rating,Current,Entry,Notes\n"

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm"

        for dive in dives.sorted(by: { $0.date > $1.date }) {
            let fields: [String] = [
                dateFormatter.string(from: dive.date),
                csvEscape(dive.location),
                csvEscape(dive.diveSite),
                "\(Int(dive.maxDepth))",
                "\(dive.bottomTime)",
                dive.waterTemp.map { "\(Int($0))" } ?? "",
                dive.visibility.map { "\($0)" } ?? "",
                csvEscape(dive.buddyName),
                "\(dive.rating)",
                dive.currentStrength?.rawValue ?? "",
                dive.entryType?.rawValue ?? "",
                csvEscape(dive.notes)
            ]
            csv += fields.joined(separator: ",") + "\n"
        }

        return csv
    }

    // MARK: - JSON Export

    static func generateJSON(from dives: [Dive]) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        if let data = try? encoder.encode(dives),
           let string = String(data: data, encoding: .utf8) {
            return string
        }
        return "[]"
    }

    // MARK: - JSON Import

    static func importJSON(from data: Data) throws -> [Dive] {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode([Dive].self, from: data)
    }

    // MARK: - Dive Log Report

    static func generateReport(from dives: [Dive]) -> String {
        let sorted = dives.sorted { $0.date > $1.date }
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short

        var report = """
        ═══════════════════════════════════════
                    REEFBUDDY DIVE LOG
        ═══════════════════════════════════════
        Generated: \(dateFormatter.string(from: Date()))
        Total Dives: \(dives.count)
        Total Bottom Time: \(dives.reduce(0) { $0 + $1.bottomTime }) min

        """

        if let deepest = dives.max(by: { $0.maxDepth < $1.maxDepth }) {
            report += "Deepest Dive: \(Int(deepest.maxDepth)) ft at \(deepest.diveSite)\n"
        }

        let uniqueSites = Set(dives.map(\.diveSite)).count
        let uniqueLocations = Set(dives.map(\.location)).count
        report += "Sites Visited: \(uniqueSites) across \(uniqueLocations) locations\n"
        report += "\n───────────────────────────────────────\n\n"

        for (index, dive) in sorted.enumerated() {
            report += "Dive #\(sorted.count - index)\n"
            report += "  Date: \(dateFormatter.string(from: dive.date))\n"
            report += "  Site: \(dive.diveSite), \(dive.location)\n"
            report += "  Depth: \(Int(dive.maxDepth)) ft | Time: \(dive.bottomTime) min\n"
            if let temp = dive.waterTemp {
                report += "  Water Temp: \(Int(temp))°F\n"
            }
            if let vis = dive.visibility {
                report += "  Visibility: \(vis) ft\n"
            }
            if !dive.buddyName.isEmpty {
                report += "  Buddy: \(dive.buddyName)\n"
            }
            if let entry = dive.entryType {
                report += "  Entry: \(entry.rawValue)\n"
            }
            if let current = dive.currentStrength {
                report += "  Current: \(current.rawValue)\n"
            }
            report += "  Rating: \(String(repeating: "★", count: dive.rating))\(String(repeating: "☆", count: 5 - dive.rating))\n"
            if !dive.notes.isEmpty {
                report += "  Notes: \(dive.notes)\n"
            }
            report += "\n"
        }

        report += "───────────────────────────────────────\n"
        report += "— Generated by ReefBuddy\n"

        return report
    }

    // MARK: - File URLs

    static func writeToTempFile(content: String, filename: String) -> URL? {
        let tempDir = FileManager.default.temporaryDirectory
        let fileURL = tempDir.appendingPathComponent(filename)
        do {
            try content.write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            return nil
        }
    }

    // MARK: - Helpers

    private static func csvEscape(_ text: String) -> String {
        if text.contains(",") || text.contains("\"") || text.contains("\n") {
            return "\"" + text.replacingOccurrences(of: "\"", with: "\"\"") + "\""
        }
        return text
    }
}

// MARK: - JSON Document for file picker

struct DiveLogDocument: FileDocument {
    static var readableContentTypes: [UTType] { [.json] }

    var data: Data

    init(data: Data = Data()) {
        self.data = data
    }

    init(configuration: ReadConfiguration) throws {
        if let fileData = configuration.file.regularFileContents {
            self.data = fileData
        } else {
            throw CocoaError(.fileReadCorruptFile)
        }
    }

    func fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: data)
    }
}
